inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 2.7.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'telnet_server_client.gemspec'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20
  Exclude:
    - './lib/telnet_server_client/argument_parser.rb'

require:
  - rubocop-performance