inherit_mode:
  merge:
    - Exclude
AllCops:
  TargetRubyVersion: 2.7.4
  NewCops: enable
  Exclude:
    - 'telnet.gemspec'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
